### ISSUE TITLE
TypeError: 0 is read-only (only in Firefox)

### ISSUE THREAD

**Issue by ndbroadbent** [necolas/react-native-web#463]
I'm seeing `TypeError: 0 is read-only` at this line: https://github.com/necolas/react-native-web/blob/master/src/vendor/setValueForStyles/index.js#L231

```javascript
style
// CSS2Properties { transform: "rotate(0deg)" }`

styleName
// "0"

styleValue
// "transform"
```

Not sure if this is helpful, but here's whatever stacktrace I could find in the Firefox dev tools:

```
setValueForStyles http://localhost:3000/javascript/vendor/react.dll.js:47440:1
updateView http://localhost:3000/javascript/vendor/react.dll.js:5480:2
setNativeProps http://localhost:3000/javascript/vendor/react.dll.js:9981:1
ApplyAnimatedValues http://localhost:3000/javascript/vendor/react.dll.js:14663:1
callback http://localhost:3000/javascript/vendor/react.dll.js:23413:15
update http://localhost:3000/javascript/vendor/react.dll.js:14486:1
_flush/< http://localhost:3000/javascript/vendor/react.dll.js:3520:55
forEach self-hosted:5013:9
_flush http://localhost:3000/javascript/vendor/react.dll.js:3520:1
_updateValue http://localhost:3000/javascript/vendor/react.dll.js:3667:1
animate/< http://localhost:3000/javascript/vendor/react.dll.js:3636:1
onUpdate
```

(This is only happening in Firefox. Chrome is working 100%.)

**Environment (include versions)**

OS: OS X
Browser: Firefox 53
React Native for Web (version): 0.0.88
React (version): 15.4.1

**Comment by necolas** [comment]
What version specifically​? What code is producing this?

**Comment by necolas** [comment]
Ok 0.0.88. update to latest and it should be fixed

**Comment by ndbroadbent** [comment]
Uggghh, sorry about that. Updated to 0.0.94 and the error is gone.

**Comment by maszaa** [comment]
I have the newest version (0.0.98) and the same problem appears still with Firefox when I try to render [this example](http://facebook.github.io/react-native/releases/0.45/docs/animations.html#animations).

**Comment by udfalkso** [comment]
I'm having the exact same issue.  Upgrading to 0.0.94 did not solve it for me unfortunately.

It seems related to styles and specifically setNativeProps and animations.  In one case it was where I'm styling an Animated.View with an interpolated value.  In another, it's happening when I realease a Touchable Opacity button.  

One case:
<img width="467" alt="screen shot 2017-06-16 at 6 18 04 pm" src="https://user-images.githubusercontent.com/2029383/27246522-30d46364-52c0-11e7-99b0-a5db1912ed47.png">

<img width="541" alt="screen shot 2017-06-16 at 6 20 36 pm" src="https://user-images.githubusercontent.com/2029383/27246666-196aac96-52c1-11e7-8b61-3afbbcc0f6b7.png">

<img width="554" alt="screen shot 2017-06-16 at 6 19 07 pm" src="https://user-images.githubusercontent.com/2029383/27246679-3341246a-52c1-11e7-8248-a9e34a46c2d8.png">

```
  "dependencies": {
    "base64-font-loader": "^0.0.4",
    "hope": "file:./hope",
    "react": "16.0.0-alpha.6",
    "react-native": "0.43.4",
    "react-native-vector-icons": "^4.2.0",
    "react-native-web": "^0.0.94",
    "react-navigation": "^1.0.0-beta.9",
    "react-redux": "^5.0.5",
    "redux": "^3.6.0",
    "redux-thunk": "^2.2.0"
  },
```

Any ideas?  Thanks!

**Comment by necolas** [comment]
Make sure you're on the latest version of the library, NOT using react@16 alphas, and please share example code that reproduces the issue. If it only happens with animations it might be a problem with the `Animated` dependency.

**Comment by udfalkso** [comment]
Thanks for the quick reply!  Here's the simplest case I've found that causes the issue.  It crashes in FF when you press "Press Me".  Fine in Chrome.  

```
import React from "react"
import { View, TouchableOpacity, Text, StyleSheet } from "react-native"

export default class App extends React.Component {

  _handlePress() {
    console.log("presssed")
  }

  render() {
    return (
      <View style={{ flex: 1, }} >
        <TouchableOpacity onPress={this._handlePress}>
          <Text>Press Me</Text>
        </TouchableOpacity>
      </View>
    )
  }
}
```

Package.json
```
{
  "name": "MyApp",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "web": "[ -d web/vendor-dev ] || npm run web:build:vendor-dev && NODE_ENV=development webpack-dev-server -d --host 0.0.0.0 --port 3000 --config web/webpack.config.js --inline --hot --colors"
  },
  "dependencies": {
    "react": "15.6.1",
    "react-native": "0.43.4",
    "react-native-web": "^0.0.94"
  },
  "devDependencies": {
    "add-asset-html-webpack-plugin": "^2.0.1",
    "babel-jest": "19.0.0",
    "babel-loader": "^7.0.0",
    "babel-preset-react-native": "1.9.1",
    "compression-webpack-plugin": "^0.4.0",
    "copy-webpack-plugin": "^4.0.1",
    "html-webpack-plugin": "^2.28.0",
    "http-serve": "^1.0.1",
    "jest": "19.0.2",
    "json-loader": "^0.5.4",
    "offline-plugin": "^4.7.0",
    "node-zopfli": "^2.0.2",
    "prettier": "^1.3.1",
    "react-dom": "^15.4.2",
    "react-hot-loader": "^1.3.1",
    "react-test-renderer": "16.0.0-alpha.6",
    "url-loader": "^0.5.8",
    "webpack": "^2.4.1",
    "webpack-dev-server": "^2.4.2"
  },
  "jest": {
    "preset": "react-native",
    "moduleNameMapper": {
      "react-native": "<rootDir>/../"
    }
  }
}
```

**Comment by necolas** [comment]
There are examples like that in the docs and they don't crash

**Comment by udfalkso** [comment]
But this one does crash.  Can you try it out?  Perhaps it's some conflict with my babel setup?

**Comment by necolas** [comment]
If you share a ready-made example that shows the problem, I'll take a look. Or you can run this repo's examples and show me what surfaces the problem there.

Also you're not on the latest version of the library, react-dom is in your dev dependencies, and you're not using matching minor versions of react/react-dom.

**Comment by udfalkso** [comment]
After some further digging I found that there was a cached build file on my end that was preventing this fix from being taken up.  Upgrading to the latest libs does the trick.  

Thanks for your patience and a great lib!  Sorry for the trouble.

**Comment by necolas** [comment]
No worries
